Repository roranger216/landing-page-rse, pull requests merged in 2023-03, with the labels that each got.

#6 create service
  package-lock.json
  package.json
  src/assets/img/consultation.jpg
  src/assets/img/customization.jpg
  src/assets/img/design.jpg
  src/assets/img/development.jpg
  src/assets/img/documentation.jpg
  src/assets/img/just.gif
  src/assets/img/outsource.jpg
  src/assets/img/pic.gif
  src/pages/components/service.tsx
  src/pages/index.tsx
Labels: WIP

#20 Enhancement/header/tailwind/tsx
  src/pages/components/header.tsx
  src/pages/components/hooks/scroll.tsx
  src/pages/components/register.tsx
  src/pages/main/dashboard.tsx
Labels: enhancement

#21 Editing
  package-lock.json
  package.json
  src/assets/img/f-bg.jpg
  src/pages/components/auth/signin.tsx
  src/pages/components/functions/account_alert.tsx
  src/pages/components/signIn.tsx
Labels: Ready for merge

#23 Enhancement
  src/pages/components/header.tsx
  src/pages/components/signIn.tsx
Labels: enhancement

#25 update register
  src/pages/components/hero.tsx
  src/pages/components/register.tsx
  src/pages/components/signIn.tsx
Labels: Ready for merge

#24 creating homepage
  package-lock.json
  package.json
  src/pages/components/dashboard_header.tsx
  src/pages/components/footer.tsx
  src/pages/components/header.tsx
  src/pages/homepage.tsx
  src/pages/index.tsx
Labels: WIP

#26 enhance darkmode-function
  src/assets/styles/global.css
  src/pages/components/darkmode.tsx
  src/pages/components/header.tsx
  src/pages/components/service.tsx
  tailwind.config.js
Labels: Ready for merge

#27 enhance team-darkmode
  src/assets/styles/global.css
  src/pages/components/contactpage.tsx
  src/pages/components/profiles/profile.tsx
  src/pages/components/profiles/profile2.tsx
  src/pages/components/profiles/profile3.tsx
  src/pages/components/profiles/profile4.tsx
  tailwind.config.js
Labels: Ready for merge

#28 Lp sample
  src/assets/styles/global.css
  src/pages/components/footer.tsx
  src/pages/components/header.tsx
Labels: WIP

#29 Enhancement/header
  src/assets/styles/global.css
  src/pages/components/contactpage.tsx
Labels: enhancement

#30 enhance register dark-mode
  src/pages/components/hero.tsx
  src/pages/components/register.tsx
Labels: Ready for merge

#32 Enhancement/darkmode
  src/assets/styles/global.css
  src/pages/components/footer.tsx
  src/pages/components/header.tsx
  src/pages/components/hero.tsx
  src/pages/components/register.tsx
  src/pages/components/signIn.tsx
Labels: Ready for merge

#34 Enhancement/navbar-responsiveness
  src/pages/components/contactpage.tsx
  src/pages/components/header.tsx
  src/pages/components/signIn.tsx
  src/pages/index.tsx
Labels: enhancement

#35 Enhancement/sign-in responsiveness
  src/pages/components/auth/signin.tsx
Labels: enhancement

#36 BugFix/modal
  src/assets/styles/global.css
Labels: bug, enhancement

#37 Enhancement/fix-sign-in-card
  src/assets/styles/global.css
  src/pages/components/auth/signin.tsx
Labels: enhancement

#39 Enhancement
  src/assets/styles/global.css
  src/pages/ZTrash/signIn.tsx
  src/pages/components/auth/signin.tsx
  src/pages/components/header.tsx
Labels: enhancement

#41 Fixbugs/signIn/nextjs
  src/pages/components/auth/signin.tsx
Labels: WIP

#44 Enhancement/improve file structure
  src/pages/ZTrash/signIn.tsx
  src/pages/components/auth/signin.tsx
  src/pages/components/darkmode/darkmode.tsx
  src/pages/components/landing-page/about.tsx
  src/pages/components/landing-page/contactpage.tsx
  src/pages/components/landing-page/footer.tsx
  src/pages/components/landing-page/header.tsx
  src/pages/components/landing-page/hero.tsx
  src/pages/components/landing-page/profiles/profile.tsx
  src/pages/components/landing-page/profiles/profile2.tsx
  src/pages/components/landing-page/profiles/profile3.tsx
  src/pages/components/landing-page/profiles/profile4.tsx
  src/pages/components/landing-page/register.tsx
  src/pages/components/landing-page/service.tsx
  src/pages/components/landing-page/team.tsx
  src/pages/index.tsx
  src/pages/main/darkmode_dashboard.tsx
  src/pages/main/dashboard.tsx
  src/pages/main/dashboard_header.tsx
  src/pages/main/homepage.tsx
Labels: enhancement

#46 Enhancement/admin-sidebar
  src/assets/styles/global.css
  src/pages/main/dashboard_header.tsx
  src/pages/main/homepage.tsx
Labels: enhancement

#47 Enhancement/user-dashboard
  src/pages/components/auth/signin.tsx
  src/pages/main/--empty-default.tsx
  src/pages/main/darkmode.tsx
  src/pages/main/dashboard_header.tsx
  src/pages/main/footer.tsx
  src/pages/main/settings.tsx
  src/pages/main/template.tsx
Labels: Ready for merge

#53 Enhancement/userr-nave
  src/pages/components/auth/signin.tsx
  src/pages/components/landing-page/header.tsx
  src/pages/main/darkmode.tsx
  src/pages/main/footer.tsx
  src/pages/main/template.tsx
  src/pages/main/user-information.tsx
Labels: Ready for merge
